const QUESTIONS = [
  // ══════════════════════════════════════════════════════════════
  //  FÁCILES  (diff: 0)  — 30 preguntas
  // ══════════════════════════════════════════════════════════════
  { id:  0, diff: 0, cat: 'Geografía',
    q: '¿Cuál es la capital de Francia?',
    opts: ['Londres', 'Berlín', 'Madrid', 'París'], ans: 3 },
  { id:  1, diff: 0, cat: 'Ciencia',
    q: '¿Cuántos planetas tiene el sistema solar?',
    opts: ['7', '9', '10', '8'], ans: 3 },
  { id:  2, diff: 0, cat: 'Arte',
    q: '¿Quién pintó la Mona Lisa?',
    opts: ['Miguel Ángel', 'Pablo Picasso', 'Leonardo da Vinci', 'Rafael'], ans: 2 },
  { id:  3, diff: 0, cat: 'Geografía',
    q: '¿En qué continente está Brasil?',
    opts: ['África', 'Asia', 'Europa', 'América del Sur'], ans: 3 },
  { id:  4, diff: 0, cat: 'Geografía',
    q: '¿Cuál es el océano más grande del mundo?',
    opts: ['Atlántico', 'Índico', 'Ártico', 'Pacífico'], ans: 3 },
  { id: 15, diff: 0, cat: 'Ciencia',
    q: '¿Cuántos colores tiene el arcoíris?',
    opts: ['5', '6', '8', '7'], ans: 3 },
  { id: 16, diff: 0, cat: 'Ciencia',
    q: '¿Cuál es el animal terrestre más rápido?',
    opts: ['León', 'Guepardo', 'Leopardo', 'Caballo'], ans: 1 },
  { id: 17, diff: 0, cat: 'Ciencia',
    q: '¿Cuántos días tiene un año bisiesto?',
    opts: ['364', '365', '366', '367'], ans: 2 },
  { id: 18, diff: 0, cat: 'Ciencia',
    q: '¿Cuál es el animal más grande del mundo?',
    opts: ['Elefante africano', 'Tiburón ballena', 'Ballena azul', 'Cachalote'], ans: 2 },
  { id: 19, diff: 0, cat: 'Geografía',
    q: '¿Cuál es el país más grande del mundo por superficie?',
    opts: ['China', 'Canadá', 'Estados Unidos', 'Rusia'], ans: 3 },
  { id: 30, diff: 0, cat: 'Ciencia',
    q: '¿Qué gas necesitan las plantas para realizar la fotosíntesis?',
    opts: ['Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Hidrógeno'], ans: 2 },
  { id: 31, diff: 0, cat: 'Deportes',
    q: '¿Cuántos jugadores tiene un equipo de fútbol en el campo?',
    opts: ['9', '10', '11', '12'], ans: 2 },
  { id: 32, diff: 0, cat: 'Cultura',
    q: '¿Cuál es el idioma más hablado del mundo?',
    opts: ['Inglés', 'Español', 'Chino mandarín', 'Hindi'], ans: 2 },
  { id: 33, diff: 0, cat: 'Ciencia',
    q: '¿Qué planeta está más cerca del Sol?',
    opts: ['Venus', 'Marte', 'Mercurio', 'Tierra'], ans: 2 },
  { id: 34, diff: 0, cat: 'Ciencia',
    q: '¿Cuál es el hueso más largo del cuerpo humano?',
    opts: ['Tibia', 'Húmero', 'Fémur', 'Radio'], ans: 2 },
  { id: 35, diff: 0, cat: 'Cultura',
    q: '¿De qué país es originario el sushi?',
    opts: ['China', 'Corea del Sur', 'Japón', 'Tailandia'], ans: 2 },
  { id: 36, diff: 0, cat: 'Geografía',
    q: '¿Cuántos continentes tiene la Tierra?',
    opts: ['5', '6', '7', '8'], ans: 2 },
  { id: 37, diff: 0, cat: 'Geografía',
    q: '¿Cuál es el río más largo de América del Sur?',
    opts: ['Orinoco', 'Paraná', 'Amazonas', 'Magdalena'], ans: 2 },
  { id: 38, diff: 0, cat: 'Matemáticas',
    q: '¿Cuántos lados tiene un octágono?',
    opts: ['6', '7', '9', '8'], ans: 3 },
  { id: 39, diff: 0, cat: 'Deportes',
    q: '¿En qué deporte se utiliza un volante (shuttlecock)?',
    opts: ['Tenis', 'Squash', 'Pádel', 'Bádminton'], ans: 3 },
  { id: 60, diff: 0, cat: 'Geografía',
    q: '¿Cuál es la capital de Japón?',
    opts: ['Osaka', 'Kioto', 'Tokio', 'Hiroshima'], ans: 2 },
  { id: 61, diff: 0, cat: 'Ciencia',
    q: '¿Qué gas constituye la mayor parte del aire que respiramos?',
    opts: ['Oxígeno', 'Dióxido de carbono', 'Nitrógeno', 'Hidrógeno'], ans: 2 },
  { id: 62, diff: 0, cat: 'Ciencia',
    q: '¿Cuál es el planeta más grande del sistema solar?',
    opts: ['Saturno', 'Neptuno', 'Urano', 'Júpiter'], ans: 3 },
  { id: 63, diff: 0, cat: 'Geografía',
    q: '¿En qué continente se encuentra Egipto?',
    opts: ['Asia', 'Oceanía', 'África', 'América'], ans: 2 },
  { id: 64, diff: 0, cat: 'Literatura',
    q: '¿Quién escribió "Romeo y Julieta"?',
    opts: ['Charles Dickens', 'William Shakespeare', 'Victor Hugo', 'Jane Austen'], ans: 1 },
  { id: 65, diff: 0, cat: 'Geografía',
    q: '¿Cuál es la capital de Alemania?',
    opts: ['Hamburgo', 'Múnich', 'Fráncfort', 'Berlín'], ans: 3 },
  { id: 66, diff: 0, cat: 'Deportes',
    q: '¿Cuántos jugadores tiene un equipo de baloncesto en el campo?',
    opts: ['4', '5', '6', '7'], ans: 1 },
  { id: 67, diff: 0, cat: 'Arte',
    q: '¿Quién compuso "Para Elisa" (Für Elise)?',
    opts: ['Mozart', 'Bach', 'Beethoven', 'Chopin'], ans: 2 },
  { id: 68, diff: 0, cat: 'Ciencia',
    q: '¿Qué órgano del cuerpo humano bombea la sangre?',
    opts: ['Riñón', 'Hígado', 'Pulmón', 'Corazón'], ans: 3 },
  { id: 69, diff: 0, cat: 'Geografía',
    q: '¿Cuál es la capital de Italia?',
    opts: ['Milán', 'Nápoles', 'Venecia', 'Roma'], ans: 3 },

  // ══════════════════════════════════════════════════════════════
  //  MEDIAS  (diff: 1)  — 30 preguntas
  // ══════════════════════════════════════════════════════════════
  { id:  5, diff: 1, cat: 'Historia',
    q: '¿En qué año llegó el hombre a la Luna por primera vez?',
    opts: ['1965', '1972', '1969', '1957'], ans: 2 },
  { id:  6, diff: 1, cat: 'Ciencia',
    q: '¿Qué científico formuló la teoría de la relatividad?',
    opts: ['Isaac Newton', 'Charles Darwin', 'Albert Einstein', 'Stephen Hawking'], ans: 2 },
  { id:  7, diff: 1, cat: 'Literatura',
    q: '¿Quién escribió El Quijote de la Mancha?',
    opts: ['Lope de Vega', 'Miguel de Cervantes', 'Francisco de Quevedo', 'Tirso de Molina'], ans: 1 },
  { id:  8, diff: 1, cat: 'Historia',
    q: '¿En qué año cayó el muro de Berlín?',
    opts: ['1985', '1991', '1987', '1989'], ans: 3 },
  { id:  9, diff: 1, cat: 'Arte',
    q: '¿Quién compuso la Quinta Sinfonía en Do menor?',
    opts: ['Mozart', 'Bach', 'Beethoven', 'Schubert'], ans: 2 },
  { id: 20, diff: 1, cat: 'Historia',
    q: '¿Quién fue el primer ser humano en viajar al espacio?',
    opts: ['Neil Armstrong', 'Buzz Aldrin', 'Valentina Tereshkova', 'Yuri Gagarin'], ans: 3 },
  { id: 21, diff: 1, cat: 'Geografía',
    q: '¿Cuál es la montaña más alta del mundo?',
    opts: ['K2', 'Aconcagua', 'Mont Blanc', 'Everest'], ans: 3 },
  { id: 22, diff: 1, cat: 'Historia',
    q: '¿En qué año comenzó la Primera Guerra Mundial?',
    opts: ['1910', '1914', '1918', '1916'], ans: 1 },
  { id: 23, diff: 1, cat: 'Ciencia',
    q: '¿Cuántos cromosomas tiene una célula humana normal?',
    opts: ['23', '44', '46', '48'], ans: 2 },
  { id: 24, diff: 1, cat: 'Historia',
    q: '¿En qué ciudad se celebraron los primeros Juegos Olímpicos modernos?',
    opts: ['París', 'Londres', 'Atenas', 'Roma'], ans: 2 },
  { id: 40, diff: 1, cat: 'Geografía',
    q: '¿Cuál es la capital de Australia?',
    opts: ['Sídney', 'Melbourne', 'Brisbane', 'Canberra'], ans: 3 },
  { id: 41, diff: 1, cat: 'Historia',
    q: '¿En qué año publicó Darwin "El origen de las especies"?',
    opts: ['1839', '1849', '1859', '1869'], ans: 2 },
  { id: 42, diff: 1, cat: 'Arte',
    q: '¿Quién pintó "La noche estrellada"?',
    opts: ['Claude Monet', 'Paul Gauguin', 'Vincent van Gogh', 'Paul Cézanne'], ans: 2 },
  { id: 43, diff: 1, cat: 'Geografía',
    q: '¿Cuál es el país más poblado del mundo actualmente?',
    opts: ['China', 'India', 'Estados Unidos', 'Indonesia'], ans: 1 },
  { id: 44, diff: 1, cat: 'Ciencia',
    q: '¿Qué científica ganó dos premios Nobel en distintas disciplinas?',
    opts: ['Rosalind Franklin', 'Marie Curie', 'Lise Meitner', 'Dorothy Hodgkin'], ans: 1 },
  { id: 45, diff: 1, cat: 'Historia',
    q: '¿En qué año llegó Cristóbal Colón a América?',
    opts: ['1488', '1490', '1492', '1498'], ans: 2 },
  { id: 46, diff: 1, cat: 'Geografía',
    q: '¿Cuántos países forman América del Sur?',
    opts: ['10', '11', '12', '13'], ans: 2 },
  { id: 47, diff: 1, cat: 'Ciencia',
    q: '¿Cuál es la velocidad aproximada de la luz en el vacío?',
    opts: ['150.000 km/s', '300.000 km/s', '450.000 km/s', '1.080.000 km/s'], ans: 1 },
  { id: 48, diff: 1, cat: 'Literatura',
    q: '¿Quién escribió "Cien años de soledad"?',
    opts: ['Mario Vargas Llosa', 'Julio Cortázar', 'Gabriel García Márquez', 'Carlos Fuentes'], ans: 2 },
  { id: 49, diff: 1, cat: 'Geografía',
    q: '¿Qué país tiene mayor número de volcanes activos en el mundo?',
    opts: ['Japón', 'Indonesia', 'México', 'Islandia'], ans: 1 },
  { id: 70, diff: 1, cat: 'Arte',
    q: '¿Quién pintó el techo de la Capilla Sixtina?',
    opts: ['Leonardo da Vinci', 'Rafael Sanzio', 'Miguel Ángel', 'Donatello'], ans: 2 },
  { id: 71, diff: 1, cat: 'Geografía',
    q: '¿Cuál es el lago más profundo del mundo?',
    opts: ['Lago Tanganica', 'Mar Caspio', 'Lago Superior', 'Lago Baikal'], ans: 3 },
  { id: 72, diff: 1, cat: 'Ciencia',
    q: '¿Cuántos elementos químicos contiene la tabla periódica actual?',
    opts: ['108', '112', '118', '126'], ans: 2 },
  { id: 73, diff: 1, cat: 'Historia',
    q: '¿En qué año se inauguró la Torre Eiffel?',
    opts: ['1879', '1885', '1889', '1895'], ans: 2 },
  { id: 74, diff: 1, cat: 'Geografía',
    q: '¿Cuál es el desierto caliente más grande del mundo?',
    opts: ['Arábigo', 'Gobi', 'Kalahari', 'Sahara'], ans: 3 },
  { id: 75, diff: 1, cat: 'Historia',
    q: '¿En qué año comenzó la Revolución Francesa?',
    opts: ['1779', '1785', '1789', '1793'], ans: 2 },
  { id: 76, diff: 1, cat: 'Literatura',
    q: '¿Quién escribió "Crimen y castigo"?',
    opts: ['León Tolstói', 'Antón Chéjov', 'Fiódor Dostoyevski', 'Iván Turguénev'], ans: 2 },
  { id: 77, diff: 1, cat: 'Ciencia',
    q: '¿Cómo se denomina la unidad básica de la herencia genética?',
    opts: ['Cromosoma', 'ARN', 'Gen', 'Proteína'], ans: 2 },
  { id: 78, diff: 1, cat: 'Literatura',
    q: '¿En qué año se publicó la primera parte de "Don Quijote"?',
    opts: ['1595', '1600', '1605', '1615'], ans: 2 },
  { id: 79, diff: 1, cat: 'Arte',
    q: '¿Quién compuso "Las cuatro estaciones"?',
    opts: ['Johann Sebastian Bach', 'Georg Händel', 'Antonio Vivaldi', 'Claudio Monteverdi'], ans: 2 },

  // ══════════════════════════════════════════════════════════════
  //  DIFÍCILES  (diff: 2)  — 30 preguntas
  // ══════════════════════════════════════════════════════════════
  { id: 10, diff: 2, cat: 'Ciencia',
    q: '¿Cuál es el elemento químico con símbolo "Au"?',
    opts: ['Plata', 'Aluminio', 'Argón', 'Oro'], ans: 3 },
  { id: 11, diff: 2, cat: 'Historia',
    q: '¿En qué año se fundó la Organización de las Naciones Unidas?',
    opts: ['1944', '1948', '1950', '1945'], ans: 3 },
  { id: 12, diff: 2, cat: 'Filosofía',
    q: '¿Qué filósofo escribió "El mundo como voluntad y representación"?',
    opts: ['Immanuel Kant', 'Georg Hegel', 'Arthur Schopenhauer', 'Friedrich Nietzsche'], ans: 2 },
  { id: 13, diff: 2, cat: 'Ciencia',
    q: '¿Cuántos huesos tiene el cuerpo humano adulto?',
    opts: ['196', '186', '206', '216'], ans: 2 },
  { id: 14, diff: 2, cat: 'Ciencia',
    q: '¿Cuál es el segundo elemento más abundante en el universo?',
    opts: ['Oxígeno', 'Helio', 'Carbono', 'Nitrógeno'], ans: 1 },
  { id: 25, diff: 2, cat: 'Geografía',
    q: '¿Cuál es la capital de Mongolia?',
    opts: ['Astana', 'Ulán Bator', 'Taskent', 'Biskek'], ans: 1 },
  { id: 26, diff: 2, cat: 'Arte',
    q: '¿En qué año nació Leonardo da Vinci?',
    opts: ['1432', '1452', '1467', '1478'], ans: 1 },
  { id: 27, diff: 2, cat: 'Literatura',
    q: '¿Qué escritor ganó el Premio Nobel de Literatura en 1982?',
    opts: ['Mario Vargas Llosa', 'Jorge Luis Borges', 'Gabriel García Márquez', 'Pablo Neruda'], ans: 2 },
  { id: 28, diff: 2, cat: 'Ciencia',
    q: '¿Cuál es la fórmula química del agua oxigenada?',
    opts: ['H2O', 'H2O2', 'HO2', 'H3O'], ans: 1 },
  { id: 29, diff: 2, cat: 'Literatura',
    q: '¿Quién escribió "En busca del tiempo perdido"?',
    opts: ['James Joyce', 'Franz Kafka', 'Marcel Proust', 'Virginia Woolf'], ans: 2 },
  { id: 50, diff: 2, cat: 'Historia',
    q: '¿En qué año se proclamó la Declaración Universal de los Derechos Humanos?',
    opts: ['1945', '1946', '1948', '1950'], ans: 2 },
  { id: 51, diff: 2, cat: 'Matemáticas',
    q: '¿Quién formuló el teorema de la incompletitud?',
    opts: ['Bertrand Russell', 'David Hilbert', 'Kurt Gödel', 'Alan Turing'], ans: 2 },
  { id: 52, diff: 2, cat: 'Geografía',
    q: '¿Cuál es la capital de Kazajistán?',
    opts: ['Almaty', 'Astana', 'Taskent', 'Bakú'], ans: 1 },
  { id: 53, diff: 2, cat: 'Historia',
    q: '¿En qué año desarrolló Jenner la primera vacuna de la historia?',
    opts: ['1776', '1796', '1816', '1836'], ans: 1 },
  { id: 54, diff: 2, cat: 'Historia',
    q: '¿En qué año descubrió Fleming la penicilina?',
    opts: ['1918', '1922', '1928', '1935'], ans: 2 },
  { id: 55, diff: 2, cat: 'Ciencia',
    q: '¿Cuál es el número atómico del carbono?',
    opts: ['4', '6', '8', '12'], ans: 1 },
  { id: 56, diff: 2, cat: 'Historia',
    q: '¿Qué tratado puso fin a la Primera Guerra Mundial?',
    opts: ['Tratado de Utrecht', 'Tratado de Versalles', 'Tratado de Westfalia', 'Tratado de París'], ans: 1 },
  { id: 57, diff: 2, cat: 'Historia',
    q: '¿En qué año se publicó "El capital" de Karl Marx?',
    opts: ['1848', '1859', '1867', '1875'], ans: 2 },
  { id: 58, diff: 2, cat: 'Ciencia',
    q: '¿Cómo se llama el efecto por el que la frecuencia de una onda varía según el movimiento de la fuente?',
    opts: ['Efecto Joule', 'Efecto Doppler', 'Efecto Hall', 'Efecto Compton'], ans: 1 },
  { id: 59, diff: 2, cat: 'Historia',
    q: '¿Qué país fue el primero en conceder el derecho al voto a las mujeres?',
    opts: ['Finlandia', 'Australia', 'Nueva Zelanda', 'Noruega'], ans: 2 },
  { id: 80, diff: 2, cat: 'Filosofía',
    q: '¿Qué filósofo griego escribió "La república"?',
    opts: ['Aristóteles', 'Sócrates', 'Platón', 'Epicuro'], ans: 2 },
  { id: 81, diff: 2, cat: 'Ciencia',
    q: '¿Quién formuló el principio de incertidumbre en mecánica cuántica?',
    opts: ['Niels Bohr', 'Erwin Schrödinger', 'Max Planck', 'Werner Heisenberg'], ans: 3 },
  { id: 82, diff: 2, cat: 'Historia',
    q: '¿En qué año se abolió la esclavitud en Brasil, último país de América en hacerlo?',
    opts: ['1858', '1868', '1878', '1888'], ans: 3 },
  { id: 83, diff: 2, cat: 'Matemáticas',
    q: '¿Quién demostró el Último Teorema de Fermat en 1995?',
    opts: ['John Nash', 'Paul Erdős', 'Andrew Wiles', 'Grigori Perelmán'], ans: 2 },
  { id: 84, diff: 2, cat: 'Arte',
    q: '¿En qué ciudad nació Wolfgang Amadeus Mozart?',
    opts: ['Viena', 'Salzburgo', 'Múnich', 'Praga'], ans: 1 },
  { id: 85, diff: 2, cat: 'Historia',
    q: '¿En qué año se firmó la Carta Magna inglesa?',
    opts: ['1115', '1215', '1315', '1415'], ans: 1 },
  { id: 86, diff: 2, cat: 'Ciencia',
    q: '¿Qué partícula subatómica no tiene carga eléctrica?',
    opts: ['Protón', 'Electrón', 'Neutrón', 'Positrón'], ans: 2 },
  { id: 87, diff: 2, cat: 'Historia',
    q: '¿En qué año fundó Alejandro Magno la ciudad de Alejandría en Egipto?',
    opts: ['356 a.C.', '344 a.C.', '331 a.C.', '323 a.C.'], ans: 2 },
  { id: 88, diff: 2, cat: 'Literatura',
    q: '¿Cuántos cantos tiene en total "La Divina Comedia" de Dante Alighieri?',
    opts: ['90', '100', '110', '120'], ans: 1 },
  { id: 89, diff: 2, cat: 'Historia',
    q: '¿En qué año proclamó Napoleón Bonaparte el Imperio Francés?',
    opts: ['1802', '1804', '1806', '1808'], ans: 1 },
];
